title: LiquidJava Docs
theme: just-the-docs
color_scheme: liquidjava
liquidjava_api_version: 0.0.4
liquidjava_repo_url: https://github.com/liquid-java/liquidjava
liquidjava_examples_url: https://github.com/liquid-java/liquidjava-examples
liquidjava_examples_codespaces_url: https://codespaces.new/liquid-java/liquidjava-examples
liquidjava_tutorial_url: https://github.com/liquid-java/liquidjava-tutorial

url: https://liquid-java.github.io
baseurl: /liquidjava-docs

permalink: pretty
search_enabled: true
heading_anchors: true

favicon_ico: "/assets/images/favicon.ico"

gh_edit_link: true
gh_edit_repository: https://github.com/liquid-java/docs
gh_edit_branch: main
gh_edit_source: /
gh_edit_view_mode: tree

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warn:
    title: Warning
    color: yellow

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - .DS_Store
  - vendor
  - Gemfile
  - Gemfile.lock
